<h1>Inhaltsverzeichnis<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Einleitung" data-toc-modified-id="Einleitung-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Einleitung</a></span></li><li><span><a href="#Verwendeter-Datensatz" data-toc-modified-id="Verwendeter-Datensatz-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Verwendeter Datensatz</a></span></li><li><span><a href="#Daten-einlesen" data-toc-modified-id="Daten-einlesen-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Daten einlesen</a></span></li><li><span><a href="#Spalten-selektieren,-Daten-plotten" data-toc-modified-id="Spalten-selektieren,-Daten-plotten-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Spalten selektieren, Daten plotten</a></span></li><li><span><a href="#Daten-normalisieren" data-toc-modified-id="Daten-normalisieren-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Daten normalisieren</a></span></li><li><span><a href="#Trainings--und-Testdaten-definieren" data-toc-modified-id="Trainings--und-Testdaten-definieren-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Trainings- und Testdaten definieren</a></span></li><li><span><a href="#MLP-vorbereiten" data-toc-modified-id="MLP-vorbereiten-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>MLP vorbereiten</a></span></li><li><span><a href="#MLP-trainieren" data-toc-modified-id="MLP-trainieren-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>MLP trainieren</a></span></li><li><span><a href="#Modell-testen/anwenden" data-toc-modified-id="Modell-testen/anwenden-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Modell testen/anwenden</a></span></li><li><span><a href="#Modell-speichern" data-toc-modified-id="Modell-speichern-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Modell speichern</a></span></li><li><span><a href="#Modell-wiederherstellen-und-anwenden" data-toc-modified-id="Modell-wiederherstellen-und-anwenden-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Modell wiederherstellen und anwenden</a></span></li></ul></div>

# Einleitung

In diesem Jupyter-Notebook durchlaufen wir alle relevanten Schritte des Machine-Learnings:
1. Daten einlesen
2. Daten vorverarbeiten
3. Trainings- und Testdaten vorbereiten
4. Machine-Learning Modell definieren (hier: ein MLP)
5. Modell trainieren
6. Modell testen/anwenden
7. Modell speichern/wiederherstellen

# Verwendeter Datensatz

Wir wollen mit realen Daten arbeiten. Bei [Kaggle](https://www.kaggle.com/) können wir viele Datensätze finden. Diesen hier verwenden wir im Folgenden:

https://www.kaggle.com/c/house-prices-advanced-regression-techniques

Der Datensatz enthält in den Trainingsdaten 1460 Beispiele von Häusern, wobei deren Eigenschaften und deren jeweiliger tatsächlicher Verkaufspreis aufgeführt ist.

# Daten einlesen

Die Datensätze liegen often als .csv Dateien vor. Diese können mittels der Bibliothek Pandas einfach eingelesen werden.

Wenn Pandas noch installiert ist, kann diese Bibliothek mittels

    pip install pandas

unter der Anaconda Prompt installiert werden.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [2]:
import pandas as pd
print(pd.__version__)

0.25.3


In [3]:
df = pd.read_csv("daten/train.csv")

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [6]:
df[0:3]

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  

[3 rows x 81 columns]

In [7]:
df.shape

(1460, 81)

In [8]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

# Spalten selektieren, Daten plotten

In [9]:
df["YearBuilt"]

0       2003
1       1976
2       2001
3       1915
4       2000
        ... 
1455    1999
1456    1978
1457    1941
1458    1950
1459    1965
Name: YearBuilt, Length: 1460, dtype: int64

In [10]:
df["SalePrice"]

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [11]:
x = df["YearBuilt"]
y = df["SalePrice"]

In [12]:
import matplotlib.pyplot as plt
plt.scatter(x,y, marker="+")
plt.show()

<Figure size 640x480 with 1 Axes>

In [108]:
data_input = df[["YearBuilt", "LotArea"]].values
#data_input = df[["YearBuilt", "LotArea", "OverallQual"]].values

nr_inputs = data_input.shape[1]

In [109]:
nr_inputs

2

In [110]:
data_input

array([[ 2003,  8450],
       [ 1976,  9600],
       [ 2001, 11250],
       ...,
       [ 1941,  9042],
       [ 1950,  9717],
       [ 1965,  9937]], dtype=int64)

In [111]:
data_output = df["SalePrice"].values

In [112]:
data_output

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

# Daten normalisieren

In [113]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [114]:
scaler_input = MinMaxScaler(feature_range=(0, 1))
scaled_input_data = scaler_input.fit_transform(data_input)

In [115]:
scaled_input_data

array([[0.94927536, 0.0334198 ],
       [0.75362319, 0.03879502],
       [0.93478261, 0.04650728],
       ...,
       [0.5       , 0.03618687],
       [0.56521739, 0.03934189],
       [0.67391304, 0.04037019]])

In [116]:
type(scaled_input_data)

numpy.ndarray

In [117]:
scaler_output = MinMaxScaler(feature_range=(0, 1))
scaled_output_data = scaler_output.fit_transform(data_output.reshape(-1,1))

In [118]:
scaled_output_data

array([[0.24107763],
       [0.20358284],
       [0.26190807],
       ...,
       [0.321622  ],
       [0.14890293],
       [0.15636717]])

# Trainings- und Testdaten definieren

In [119]:
x_train = scaled_input_data[0:1000]
y_train = scaled_output_data[0:1000]
x_test  = scaled_input_data[1000:]
y_test  = scaled_output_data[1000:]

In [120]:
x_train.shape

(1000, 2)

In [121]:
y_train.shape

(1000, 1)

In [122]:
x_test.shape

(460, 2)

In [123]:
y_test.shape

(460, 1)

In [124]:
print(x_train[0], "-->", y_train[0])

[0.94927536 0.0334198 ] --> [0.24107763]


# MLP vorbereiten

In [132]:
from tensorflow import keras

tf.keras.backend.clear_session()

model = keras.Sequential()
model.add(keras.layers.Dense(10,
                             activation="relu",
                             input_shape=(nr_inputs,)))
model.add(keras.layers.Dense(1,
                             activation="linear"))

In [133]:
model.compile(optimizer='sgd',               
              loss=tf.keras.losses.MeanSquaredError(),
              metrics=['accuracy'])

In [134]:
model.build()

In [135]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                30        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


# MLP trainieren

In [136]:
history = model.fit(x_train,
                    y_train,
                    epochs=200)

Train on 1000 samples
Epoch 1/200
1000/1000 [==============================] - 0s 243us/sample - loss: 0.0124 - accuracy: 0.0010
Epoch 2/200
1000/1000 [==============================] - 0s 50us/sample - loss: 0.0085 - accuracy: 0.0010
Epoch 3/200
1000/1000 [==============================] - 0s 39us/sample - loss: 0.0083 - accuracy: 0.0010
Epoch 4/200
1000/1000 [==============================] - 0s 41us/sample - loss: 0.0083 - accuracy: 0.0010
Epoch 5/200
1000/1000 [==============================] - 0s 42us/sample - loss: 0.0083 - accuracy: 0.0010
Epoch 6/200
1000/1000 [==============================] - 0s 40us/sample - loss: 0.0082 - accuracy: 0.0010
Epoch 7/200
1000/1000 [==============================] - 0s 40us/sample - loss: 0.0082 - accuracy: 0.0010
Epoch 8/200
1000/1000 [==============================] - 0s 42us/sample - loss: 0.0082 - accuracy: 0.0010
Epoch 9/200
1000/1000 [==============================] - 0s 45us/sample - loss: 0.0082 - accuracy: 0.0010
Epoch 10/200
1000/1000 

1000/1000 [==============================] - 0s 51us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 154/200
1000/1000 [==============================] - 0s 51us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 155/200
1000/1000 [==============================] - 0s 53us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 156/200
1000/1000 [==============================] - 0s 58us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 157/200
1000/1000 [==============================] - 0s 54us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 158/200
1000/1000 [==============================] - 0s 53us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 159/200
1000/1000 [==============================] - 0s 50us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 160/200
1000/1000 [==============================] - 0s 43us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 161/200
1000/1000 [==============================] - 0s 52us/sample - loss: 0.0080 - accuracy: 0.0010
Epoch 162/200
1000/1000 [=================

# Modell testen/anwenden

In [137]:
preds = model.predict(x_test)

In [138]:
preds.shape

(460, 1)

In [139]:
preds[0:5]

array([[0.16285498],
       [0.08715994],
       [0.27294645],
       [0.21321559],
       [0.24665065]], dtype=float32)

In [140]:
preds_dollar = scaler_output.inverse_transform( preds )

In [141]:
preds_dollar.shape

(460, 1)

In [142]:
preds_dollar[:10]

array([[152171.88 ],
       [ 97663.875],
       [231448.73 ],
       [188436.55 ],
       [212513.14 ],
       [183616.14 ],
       [181325.4  ],
       [161469.45 ],
       [228963.81 ],
       [107282.48 ]], dtype=float32)

In [143]:
gt_dollar = scaler_output.inverse_transform( y_test )

In [144]:
gt_dollar.shape

(460, 1)

In [145]:
gt_dollar[:10]

array([[ 82000.],
       [ 86000.],
       [232000.],
       [136905.],
       [181000.],
       [149900.],
       [163500.],
       [ 88000.],
       [240000.],
       [102000.]])

In [147]:
nr_tests = len(y_test)
sum_errors = 0.0
for i in range(0,nr_tests):
    error = gt_dollar[i] - preds_dollar[i]
    print("{0} vs {1} --> Fehler: {2}"
          .format(preds_dollar[i],
                  gt_dollar[i],
                  error ))
    sum_errors += abs(error)
print("Durchschnittlicher Fehler in $:", sum_errors/nr_tests)

[152171.88] vs [82000.] --> Fehler: [-70171.875]
[97663.875] vs [86000.] --> Fehler: [-11663.875]
[231448.73] vs [232000.] --> Fehler: [551.265625]
[188436.55] vs [136905.] --> Fehler: [-51531.546875]
[212513.14] vs [181000.] --> Fehler: [-31513.140625]
[183616.14] vs [149900.] --> Fehler: [-33716.140625]
[181325.4] vs [163500.] --> Fehler: [-17825.40625]
[161469.45] vs [88000.] --> Fehler: [-73469.453125]
[228963.81] vs [240000.] --> Fehler: [11036.1875]
[107282.48] vs [102000.] --> Fehler: [-5282.4765625]
[168696.31] vs [135000.] --> Fehler: [-33696.3125]
[169653.58] vs [100000.] --> Fehler: [-69653.578125]
[112247.305] vs [165000.] --> Fehler: [52752.6953125]
[87227.195] vs [85000.] --> Fehler: [-2227.1953125]
[149471.73] vs [119200.] --> Fehler: [-30271.734375]
[217325.39] vs [227000.] --> Fehler: [9674.609375]
[217267.86] vs [203000.] --> Fehler: [-14267.859375]
[188302.44] vs [187500.] --> Fehler: [-802.4375]
[208055.55] vs [160000.] --> Fehler: [-48055.546875]
[212175.48] vs [21

# Modell speichern

In [156]:
fname1 = "hauspreis_schaetzer.h5"
model.save(fname1)

In [157]:
import pickle
fname2 = "scaler_output.pkl"
fobj = open(fname2, "wb")
pickle.dump(scaler_output, fobj)
fobj.close()

# Modell wiederherstellen und anwenden

In [158]:
new_model = keras.models.load_model(fname1)

In [159]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                30        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [161]:
import pickle
fobj = open(fname2, "rb")
scaler = pickle.load(fobj)

In [162]:
type(scaler)

sklearn.preprocessing.data.MinMaxScaler

In [163]:
test_sample = np.array( [[0.94927536, 0.0334198 ]] )

In [164]:
test_sample.shape

(1, 2)

In [165]:
pred = new_model.predict( test_sample )

In [166]:
pred

array([[0.2573697]], dtype=float32)

In [167]:
scaler.inverse_transform( pred )

array([[220231.92]], dtype=float32)